include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for V2Ray Server
LUCI_DEPENDS:=+xray-core
LUCI_PKGARCH:=all

PKG_VERSION:=1.1
PKG_MAINTAINER:=OpenWrt LuCI community

include $(TOPDIR)/feeds/luci/luci.mk